Do not catch critical errors and do not clear log
jungvonmatt/contentful-ssg pull request #9
Opened 2021-06-04 14:25 UTC by tharders

- Errors in the build are forwarded, so that a buid process will stop (For example an error in transform function or syntax error in contentful-ssg file)
- task logging is changed so that logs in custom code are kept
- update some formatting (to match prettier rules)

2021-06-07 21:29 UTC, bezoerb requested changes

2021-06-07 21:29 UTC, bezoerb commented on lib/dump.js
> -const UpdaterRenderer = require('listr-update-renderer');
There's no need to replace `listr-update-renderer` with a custom one.
Error logging works fine as long as they are not caught inside `lib/dump.js` 
<img width="589" alt="Bildschirmfoto 2021-06-07 um 23 16 14" src="https://user-images.githubusercontent.com/1697800/121089261-2e1da680-c7e7-11eb-803b-4d8d6938ec03.png">

2021-06-07 21:29 UTC, bezoerb commented on test/localize.test.js
> +        url:
this breaks the linter on my side ;)

2021-06-07 21:29 UTC, bezoerb commented on test/mapper.test.js
> +        url:
s.o.

2021-06-08 10:52 UTC, tharders commented on lib/dump.js
> -const UpdaterRenderer = require('listr-update-renderer');
Aber ein console.log wird geschluckt.
Ich finde der update renderer bringt nicht wirklich einen mehrwehrt außer der netten progress spielerei.
Da habe ich lieber einen renderer der nix schluckt und man kann dann zwischendrin vernünftig logs ausgeben.
Zum beispiel "entry hat nicht alle mandatory felder"

2021-06-09 09:28 UTC, bezoerb approved these changes

2021-06-09 09:28 UTC, merged